{"trial_id": "01", "hyperparameters": {"space": [{"class_name": "Int", "config": {"name": "units_1", "default": null, "conditions": [], "min_value": 16, "max_value": 128, "step": 16, "sampling": "linear"}}, {"class_name": "Choice", "config": {"name": "activation_1", "default": "relu", "conditions": [], "values": ["relu", "elu"], "ordered": false}}, {"class_name": "Int", "config": {"name": "units_2", "default": null, "conditions": [], "min_value": 8, "max_value": 64, "step": 8, "sampling": "linear"}}, {"class_name": "Choice", "config": {"name": "activation_2", "default": "relu", "conditions": [], "values": ["relu", "elu"], "ordered": false}}, {"class_name": "Choice", "config": {"name": "lr", "default": 0.01, "conditions": [], "values": [0.01, 0.001, 0.0005], "ordered": true}}], "values": {"units_1": 128, "activation_1": "relu", "units_2": 48, "activation_2": "elu", "lr": 0.001}}, "metrics": {"metrics": {}}, "score": null, "best_step": 0, "status": "FAILED", "message": "Traceback (most recent call last):\n  File \"/Users/martinagarciagonzalez/Library/Python/3.12/lib/python/site-packages/keras_tuner/src/engine/base_tuner.py\", line 274, in _try_run_and_update_trial\n    self._run_and_update_trial(trial, *fit_args, **fit_kwargs)\n  File \"/Users/martinagarciagonzalez/Library/Python/3.12/lib/python/site-packages/keras_tuner/src/engine/base_tuner.py\", line 265, in _run_and_update_trial\n    tuner_utils.convert_to_metrics_dict(\n  File \"/Users/martinagarciagonzalez/Library/Python/3.12/lib/python/site-packages/keras_tuner/src/engine/tuner_utils.py\", line 132, in convert_to_metrics_dict\n    [convert_to_metrics_dict(elem, objective) for elem in results]\n     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/Users/martinagarciagonzalez/Library/Python/3.12/lib/python/site-packages/keras_tuner/src/engine/tuner_utils.py\", line 145, in convert_to_metrics_dict\n    best_value, _ = _get_best_value_and_best_epoch_from_history(\n                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/Users/martinagarciagonzalez/Library/Python/3.12/lib/python/site-packages/keras_tuner/src/engine/tuner_utils.py\", line 116, in _get_best_value_and_best_epoch_from_history\n    objective_value = objective.get_value(metrics)\n                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/Users/martinagarciagonzalez/Library/Python/3.12/lib/python/site-packages/keras_tuner/src/engine/objective.py\", line 59, in get_value\n    return logs[self.name]\n           ~~~~^^^^^^^^^^^\nKeyError: 'val_recall'\n"}